using Dapper;

namespace StockTrading.Data;

public sealed class DapperDatabaseInitializer(IDbConnectionFactory connectionFactory) : IDatabaseInitializer
{
    public async Task InitializeAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = await connectionFactory.CreateOpenConnectionAsync(cancellationToken);
        await connection.ExecuteAsync(Sql);
    }

    private const string Sql = """
        create table if not exists roles (
            id integer primary key,
            name varchar(100) not null unique,
            normalized_name varchar(100) not null unique,
            created_at_utc timestamptz not null
        );

        create table if not exists users (
            id integer generated by default as identity primary key,
            name varchar(200) not null,
            email varchar(320) null unique,
            normalized_email varchar(320) null unique,
            phone_number varchar(20) null unique,
            normalized_phone_number varchar(20) null unique,
            is_active boolean not null default true,
            created_at_utc timestamptz not null
        );

        create table if not exists user_roles (
            user_id integer not null references users(id) on delete cascade,
            role_id integer not null references roles(id) on delete cascade,
            primary key (user_id, role_id)
        );

        create table if not exists user_otps (
            id bigserial primary key,
            user_id integer not null references users(id) on delete cascade,
            login_method integer not null default 2,
            otp_hash text not null,
            expires_at_utc timestamptz not null,
            consumed_at_utc timestamptz null,
            created_at_utc timestamptz not null
        );

        create index if not exists ix_user_otps_user_id_expires_at_utc
            on user_otps(user_id, expires_at_utc);

        create table if not exists stocks (
            id integer generated by default as identity primary key,
            symbol varchar(100) not null,
            exchange varchar(20) not null,
            symbol_token varchar(100) not null,
            trading_symbol varchar(100) not null,
            name varchar(200) null,
            created_at_utc timestamptz not null,
            updated_at_utc timestamptz null
        );

        create unique index if not exists ux_stocks_exchange_symbol_token
            on stocks (exchange, symbol_token);

        create table if not exists stock_profiles (
            id integer generated by default as identity primary key,
            stock_id integer not null references stocks(id) on delete cascade,
            asset_type varchar(40) not null default 'Unknown',
            theme varchar(100) null,
            sector varchar(100) null,
            industry varchar(150) null,
            description text null,
            updated_by_nse boolean not null default false,
            updated_by_yahoo boolean not null default false,
            updated_by_tapetide boolean not null default false,
            classification_reason text null,
            confidence_score numeric(5, 2) null,
            dividend_yield numeric(10, 4) null,
            growth_rate numeric(10, 4) null,
            debt_to_equity numeric(10, 4) null,
            pe_ratio numeric(10, 4) null,
            earnings_per_share numeric(18, 4) null,
            price_to_book numeric(18, 4) null,
            total_revenue numeric(20, 2) null,
            net_income numeric(20, 2) null,
            total_debt numeric(20, 2) null,
            total_cash numeric(20, 2) null,
            cash_flow numeric(20, 2) null,
            market_cap numeric(20, 2) null,
            last_analyzed_at_utc timestamptz null,
            created_at_utc timestamptz not null,
            updated_at_utc timestamptz null
        );

        create unique index if not exists ux_stock_profiles_stock_id
            on stock_profiles (stock_id);

        create table if not exists market_job_decisions (
            id integer generated by default as identity primary key,
            decision_date date not null,
            exchange varchar(10) not null,
            job_name varchar(100) not null,
            is_trading_day boolean not null,
            market_open_time time not null,
            market_close_time time not null,
            jobs_enabled boolean not null,
            decision_reason text null,
            decided_at_utc timestamptz not null,
            jobs_disabled_until_utc timestamptz null,
            created_at_utc timestamptz not null,
            updated_at_utc timestamptz null
        );

        create unique index if not exists ux_market_job_decisions_date_exchange_job
            on market_job_decisions (decision_date, exchange, job_name);

        alter table if exists trade_plans
            drop column if exists watchlist_id;

        alter table if exists trade_plans
            drop column if exists watchlist_item_id;

        drop table if exists watchlist_data;

        drop table if exists watchlist;

        drop table if exists watchlist_items;

        create table if not exists trade_plans (
            id integer generated by default as identity primary key,
            stock_id integer not null references stocks(id),
            buy_price numeric(18, 4) not null,
            sell_price numeric(18, 4) not null,
            quantity integer not null,
            max_budget numeric(18, 4) null,
            status varchar(40) not null,
            is_active boolean not null default true,
            repeat_enabled boolean not null default true,
            buy_trigger_count integer not null default 0,
            sell_trigger_count integer not null default 0,
            last_buy_triggered_at_utc timestamptz null,
            last_sell_triggered_at_utc timestamptz null,
            created_at_utc timestamptz not null,
            updated_at_utc timestamptz null
        );

        alter table stock_profiles
            add column if not exists updated_by_nse boolean not null default false;

        alter table stock_profiles
            add column if not exists updated_by_yahoo boolean not null default false;

        alter table stock_profiles
            add column if not exists updated_by_tapetide boolean not null default false;

        alter table stock_profiles
            drop column if exists fundamentals_source;

        alter table stock_profiles
            add column if not exists earnings_per_share numeric(18, 4) null;

        alter table stock_profiles
            add column if not exists price_to_book numeric(18, 4) null;

        alter table stock_profiles
            add column if not exists total_revenue numeric(20, 2) null;

        alter table stock_profiles
            add column if not exists net_income numeric(20, 2) null;

        alter table stock_profiles
            add column if not exists total_debt numeric(20, 2) null;

        alter table stock_profiles
            add column if not exists total_cash numeric(20, 2) null;

        alter table stock_profiles
            add column if not exists cash_flow numeric(20, 2) null;

        alter table stock_profiles
            add column if not exists stock_category varchar(40) not null default 'Unknown';

        alter table stock_profiles
            add column if not exists stock_category_reason text null;

        alter table stock_profiles
            add column if not exists stock_category_confidence numeric(5, 2) null;

        alter table stock_profiles
            add column if not exists stock_category_updated_at_utc timestamptz null;

        create index if not exists ix_trade_plans_stock_id
            on trade_plans (stock_id);

        create table if not exists trade_plan_runs (
            id integer generated by default as identity primary key,
            trade_plan_id integer not null references trade_plans(id) on delete cascade,
            status varchar(40) not null,
            buy_order_id varchar(100) null,
            sell_order_id varchar(100) null,
            buy_price numeric(18, 4) null,
            sell_price numeric(18, 4) null,
            quantity integer not null,
            started_at_utc timestamptz not null,
            completed_at_utc timestamptz null,
            updated_at_utc timestamptz null
        );

        create index if not exists ix_trade_plan_runs_trade_plan_id
            on trade_plan_runs (trade_plan_id);

        create table if not exists broker_sessions (
            id integer generated by default as identity primary key,
            broker_name varchar(100) not null,
            user_id integer null references users(id) on delete cascade,
            access_token_encrypted text not null,
            refresh_token_encrypted text not null,
            feed_token_encrypted text null,
            access_token_expires_at_utc timestamptz null,
            refresh_token_expires_at_utc timestamptz null,
            raw_data_json text null,
            is_active boolean not null default true,
            created_at_utc timestamptz not null,
            updated_at_utc timestamptz null
        );

        create unique index if not exists ux_broker_sessions_broker_user
            on broker_sessions (broker_name, coalesce(user_id, 0));
        """;
}
